name: Pre-merge Test and Build Workflow
run-name: ${{ github.actor }}s commit is being tested!
on:


  pull_request:
    branches:
      - main
      - ra-dashboard

    # Pull request types can be found here:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - ra-dashboard

jobs:

  # #################################################
  # Python code test and lint
  # #################################################

  Lint-And-Test-Python-Lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambda
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8

      # Show versions.
      - run: python --version
      - run: poetry --version

      - run: poetry install
      - run: poetry run pylint src tests
      - run: poetry run pytest

  # #################################################
  # Test cloud formation template
  # #################################################

  Test-Cloud-Formation-Template:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloud_formation
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up node 18.16
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - run: npm install
      - run: npm run build
      - run: npm run test

  # #################################################
  # Test Website and OpenAPI Client Autogenerator
  # #################################################

  # Note: We test the api autogenerator and the website
  # together because the website needs the autogenerated
  # client to build properly.

  Test-Autogenerate-Api-and-Website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api_definition
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Java 20
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 20

      - name: Set up node 18.16
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install Api Depencencies
        working-directory: ./api_definition
        run: npm install

      - name: Build Api Client
        working-directory: ./api_definition
        run: npm run build

      - name: Install Website Depencencies
        working-directory: ./website
        run: npm install

      - name: Build Api Client
        working-directory: ./website
        run: npm run build && npm run test
